steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dragons-delivery', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dragons-delivery']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dragons-delivery'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dragons-delivery'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--cpu-throttling'
      - '--memory'
      - '128Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '3'
